drop table program_study_options cascade constraints purge;

create table program_study_options (
  program_study_option_id number generated by default as identity primary key,
  program_id      number not null,
  study_mode_id   number not null,
  duration_months number,
  constraint uq_prog_study unique (program_id, study_mode_id),
  constraint fk_pso_prog foreign key (program_id) references programs(program_id) on delete cascade,
  constraint fk_pso_mode foreign key (study_mode_id) references study_modes(study_mode_id),
  constraint ck_pso_duration check (duration_months is null or duration_months > 0)
);

merge into program_study_options tgt
using (
  with levels as (select level lvl from dual connect by level <= 6),

  mp as (
    select p.program_id, m.study_mode, m.study_mode_months,
           row_number() over (partition by p.program_id order by p.program_id) rn
    from master_programs m
    join programs p
      on p.program_name  = trim(m.program_name)
     and p.university_id = (select u.university_id
                            from universities u
                            where u.university_name = trim(m.university_name))
  ),

  base as (
    select
      program_id,
      trim(regexp_substr(study_mode,        '[^|]+', 1, l.lvl)) as mode_token,
      trim(regexp_substr(study_mode_months, '[^|]+', 1, l.lvl)) as months_by_pos,
      trim(regexp_substr(study_mode_months, '[^|]+', 1, 1))     as months_first,
      trim(regexp_substr(study_mode_months, '[^|]+', 1,
           case when study_mode_months is null then 1
                else regexp_count(study_mode_months, '\|') + 1 end)) as months_last,
      case when study_mode is null then 0
           else regexp_count(study_mode, '\|') + 1 end           as mode_cnt,
      case when study_mode_months is null then 0
           else regexp_count(study_mode_months, '\|') + 1 end    as months_cnt
    from mp join levels l on mp.rn = 1
    where regexp_substr(study_mode, '[^|]+', 1, l.lvl) is not null
  ),

  matched as (
    select program_id,
           mode_token,
           case
             when months_by_pos is not null then months_by_pos
             when months_cnt = 1           then months_first
             when months_cnt > 1           then months_last
             else null
           end as months_token
    from base
  ),

  casted as (
    select
      program_id,
      mode_token,
      case
        when months_token is not null
         then to_number(replace(trim(regexp_replace(months_token,'[^0-9.,]','')), ',', '.'))
        else null
      end as duration_months
    from matched
  ),
  keyed as (
    select
      c.program_id,
      sm.study_mode_id,
      max(c.duration_months) as duration_months
    from casted c
    join study_modes sm on sm.study_mode_name = c.mode_token
    group by c.program_id, sm.study_mode_id
  )
  select * from keyed
) src
on (tgt.program_id = src.program_id and tgt.study_mode_id = src.study_mode_id)
when not matched then
  insert (program_id, study_mode_id, duration_months)
  values (src.program_id, src.study_mode_id, src.duration_months)
when matched then
  update set tgt.duration_months = src.duration_months;