select * from master_programs;
select count(*) from master_programs;


create table universities (
  university_id    number generated by default as identity primary key,
  university_name  varchar2(300) not null,
  constraint uq_universities_name unique (university_name)
);

create table locations (
  location_id  number generated by default as identity primary key,
  city         varchar2(200),
  country      varchar2(200),
  constraint uq_locations_city_country unique (city, country)
);

create table degrees (
  degree_id   number generated by default as identity primary key,
  degree_tag  varchar2(50) not null,
  constraint uq_degrees_tag unique (degree_tag)
);

create table delivery_types (
  delivery_type_id   number generated by default as identity primary key,
  delivery_type_name varchar2(50) not null,
  constraint uq_delivery_types_name unique (delivery_type_name)
);

create table study_modes (
  study_mode_id   number generated by default as identity primary key,
  study_mode_name varchar2(50) not null,
  constraint uq_study_modes_name unique (study_mode_name)
);

create table languages (
  language_id   number generated by default as identity primary key,
  language_name varchar2(100) not null,
  constraint uq_languages_name unique (language_name)
);

create table disciplines (
  discipline_id   number generated by default as identity primary key,
  discipline_name varchar2(200) not null,
  constraint uq_disciplines_name unique (discipline_name)
);

create table language_tests (
  language_test_id number generated by default as identity primary key,
  test_name        varchar2(100) not null,
  constraint uq_language_tests_name unique (test_name)
);


create table programs (
  program_id                    number generated by default as identity primary key,
  university_id                 number not null,
  degree_id                     number,
  location_id                   number,

  program_name                  varchar2(400) not null,
  credits_ects                  number,
  review_score                  number(4,2),
  review_count                  number,
  thesis_required               char(1) check (thesis_required in ('Y','N')),
  internship_mandatory          char(1) check (internship_mandatory in ('Y','N')),

  industry_partnership_level    varchar2(10) check (industry_partnership_level in ('none','some','strong')),
  career_services_strength      varchar2(10) check (career_services_strength in ('weak','avg','strong')),
  alumni_network_strength       varchar2(10) check (alumni_network_strength in ('weak','avg','strong')),

  program_matriculation_fee     number,
  tuition_amount_eur            number,
  living_cost_eur               number,

  constraint uq_programs_univ_name unique (university_id, program_name),
  constraint fk_programs_university   foreign key (university_id)    references universities(university_id),
  constraint fk_programs_degree       foreign key (degree_id)        references degrees(degree_id),
  constraint fk_programs_location     foreign key (location_id)      references locations(location_id)
);


create table program_study_options (
  program_study_option_id number generated by default as identity primary key,
  program_id              number not null,
  study_mode_id           number not null,
  duration_months         number,
  constraint uq_prog_study unique (program_id, study_mode_id),
  constraint fk_pso_program    foreign key (program_id)    references programs(program_id) on delete cascade,
  constraint fk_pso_study_mode foreign key (study_mode_id) references study_modes(study_mode_id)
);

create table program_languages (
  program_language_id number generated by default as identity primary key,
  program_id          number not null,
  language_id         number not null,
  constraint uq_prog_language unique (program_id, language_id),
  constraint fk_pl_program  foreign key (program_id)  references programs(program_id) on delete cascade,
  constraint fk_pl_language foreign key (language_id) references languages(language_id)
);

create table program_disciplines (
  program_discipline_id number generated by default as identity primary key,
  program_id            number not null,
  discipline_id         number not null,
  constraint uq_prog_discipline unique (program_id, discipline_id),
  constraint fk_pd_program    foreign key (program_id)    references programs(program_id) on delete cascade,
  constraint fk_pd_discipline foreign key (discipline_id) references disciplines(discipline_id)
);

create table program_intakes (
  program_intake_id   number generated by default as identity primary key,
  program_id          number not null,
  intake_month_date   date not null,
  constraint uq_prog_intake unique (program_id, intake_month_date),
  constraint fk_pi_program foreign key (program_id) references programs(program_id) on delete cascade
);

create table program_application_deadlines (
  program_deadline_id number generated by default as identity primary key,
  program_id          number not null,
  deadline_month_date date not null,
  constraint uq_prog_deadline unique (program_id, deadline_month_date),
  constraint fk_pad_program foreign key (program_id) references programs(program_id) on delete cascade
);

create table program_language_requirements (
  program_language_req_id number generated by default as identity primary key,
  program_id              number not null,
  language_test_id        number not null,
  required_score_number   number,        
  score_text              varchar2(200), 
  constraint uq_prog_test unique (program_id, language_test_id),
  constraint fk_plr_program  foreign key (program_id)       references programs(program_id) on delete cascade,
  constraint fk_plr_test     foreign key (language_test_id) references language_tests(language_test_id)
);




merge into universities d
using (select distinct trim(university_name) as name from master_programs where university_name is not null) s
on (d.university_name = s.name)
when not matched then insert (university_name) values (s.name);

merge into locations d
using (
  select distinct trim(city) as city, trim(country) as country
  from master_programs
  where city is not null or country is not null
) s
on (d.city = s.city and d.country = s.country)
when not matched then insert (city, country) values (s.city, s.country);

merge into degrees d
using (select distinct trim(degree_tag_clean) as tag from master_programs where degree_tag_clean is not null) s
on (d.degree_tag = s.tag)
when not matched then insert (degree_tag) values (s.tag);


merge into delivery_types d
using (
  select distinct trim(regexp_substr(m.delivery_type_std, '[^|]+', 1, lvl)) as t
  from master_programs m
  cross join (select level as lvl from dual connect by level <= 5)
  where m.delivery_type_std is not null
    and regexp_substr(m.delivery_type_std, '[^|]+', 1, lvl) is not null
) s
on (d.delivery_type_name = s.t)
when not matched then insert (delivery_type_name) values (s.t);


merge into study_modes d
using (
  select distinct trim(regexp_substr(m.study_mode, '[^|]+', 1, lvl)) as sm
  from master_programs m
  cross join (select level as lvl from dual connect by level <= 5)
  where m.study_mode is not null
    and regexp_substr(m.study_mode, '[^|]+', 1, lvl) is not null
) s
on (d.study_mode_name = s.sm)
when not matched then insert (study_mode_name) values (s.sm);

merge into languages d
using (
  select distinct trim(regexp_substr(m.language_clean, '[^|]+', 1, lvl)) as lang
  from master_programs m
  cross join (select level as lvl from dual connect by level <= 10)
  where m.language_clean is not null
    and regexp_substr(m.language_clean, '[^|]+', 1, lvl) is not null
) s
on (d.language_name = s.lang)
when not matched then insert (language_name) values (s.lang);

merge into disciplines d
using (
  select distinct trim(regexp_substr(m.disciplines_clean, '[^|]+', 1, lvl)) as disc
  from master_programs m
  cross join (select level as lvl from dual connect by level <= 20)
  where m.disciplines_clean is not null
    and regexp_substr(m.disciplines_clean, '[^|]+', 1, lvl) is not null
) s
on (d.discipline_name = s.disc)
when not matched then insert (discipline_name) values (s.disc);


merge into language_tests d
using (
  select distinct
         case
           when regexp_like(
                  trim(regexp_replace(token, '\s*[0-9]+([.,][0-9]+)?\s*$', '')),
                  '^TOEFL', 'i'
                )
           then 'TOEFL iBT'
           when regexp_like(
                  trim(regexp_replace(token, '\s*[0-9]+([.,][0-9]+)?\s*$', '')),
                  'DUOLINGO', 'i'
                )
           then 'Duolingo English Test'
           else regexp_replace(
                  trim(regexp_replace(token, '\s*[0-9]+([.,][0-9]+)?\s*$', '')),
                  '[[:space:]]+', ' '
                )
         end as test_name
  from (
    select trim(regexp_substr(m.language_requirements_std, '[^|]+', 1, t.lvl)) as token
    from master_programs m
    cross join (select level as lvl from dual connect by level <= 10) t
    where m.language_requirements_std is not null
      and regexp_substr(m.language_requirements_std, '[^|]+', 1, t.lvl) is not null
  )
) s
on (d.test_name = s.test_name)
when not matched then
  insert (test_name) values (s.test_name);



merge into programs d
using (
  select *
  from (
    select
      u.university_id,
      trim(m.program_name) as program_name,
      dg.degree_id,
      l.location_id,
      cast(nullif(trim(m.credits_ects), '') as number)     as credits_ects,
      cast(nullif(trim(m.review_score), '') as number)     as review_score,
      cast(nullif(trim(m.review_count), '') as number)     as review_count,

      case lower(trim(m.thesis_required))
        when 'yes' then 'Y' when 'y' then 'Y' when 'true' then 'Y' else 'N' end as thesis_required,
      case lower(trim(m.internship_mandatory))
        when 'yes' then 'Y' when 'y' then 'Y' when 'true' then 'Y' else 'N' end as internship_mandatory,

      lower(trim(m.industry_partnership_level)) as industry_partnership_level,
      lower(trim(m.career_services_strength))   as career_services_strength,
      lower(trim(m.alumni_network_strength))    as alumni_network_strength,

      cast(nullif(trim(m.program_matriculation_fee), '') as number) as program_matriculation_fee,
      cast(nullif(trim(m.tuition_amount_eur), '') as number)        as tuition_amount_eur,
      cast(nullif(trim(m.living_cost_eur), '') as number)           as living_cost_eur,

      row_number() over (
        partition by u.university_id, trim(m.program_name)
        order by
          nvl(cast(nullif(trim(m.review_count), '') as number), 0) desc,
          nvl(cast(nullif(trim(m.review_score), '') as number), -1) desc,
          trim(m.delivery_type_std) nulls last
      ) as rn
    from master_programs m
    join universities   u  on u.university_name = trim(m.university_name)
    left join degrees   dg on dg.degree_tag     = trim(m.degree_tag_clean)
    left join locations l  on l.city            = trim(m.city) and l.country = trim(m.country)
    where m.program_name is not null
  )
  where rn = 1
) s
on (d.university_id = s.university_id and d.program_name = s.program_name)
when not matched then insert (
  university_id, degree_id, location_id,
  program_name, credits_ects, review_score, review_count,
  thesis_required, internship_mandatory,
  industry_partnership_level, career_services_strength, alumni_network_strength,
  program_matriculation_fee, tuition_amount_eur, living_cost_eur
) values (
  s.university_id, s.degree_id, s.location_id,
  s.program_name, s.credits_ects, s.review_score, s.review_count,
  s.thesis_required, s.internship_mandatory,
  s.industry_partnership_level, s.career_services_strength, s.alumni_network_strength,
  s.program_matriculation_fee, s.tuition_amount_eur, s.living_cost_eur
);

create table program_delivery_types (
  program_id       number not null,
  delivery_type_id number not null,
  constraint pk_program_delivery_types primary key (program_id, delivery_type_id),
  constraint fk_pdt_prog foreign key (program_id) references programs(program_id) on delete cascade,
  constraint fk_pdt_del  foreign key (delivery_type_id) references delivery_types(delivery_type_id)
);

merge into program_delivery_types tgt
using (
  select distinct p.program_id, dt.delivery_type_id
  from master_programs m
  join programs p
    on p.program_name = trim(m.program_name)
   and p.university_id = (
         select u.university_id from universities u where u.university_name = trim(m.university_name)
       )
  cross join (select level as lvl from dual connect by level <= 5)
  join delivery_types dt
    on dt.delivery_type_name = trim(regexp_substr(m.delivery_type_std, '[^|]+', 1, lvl))
  where m.delivery_type_std is not null
    and regexp_substr(m.delivery_type_std, '[^|]+', 1, lvl) is not null
) src
on (tgt.program_id = src.program_id and tgt.delivery_type_id = src.delivery_type_id)
when not matched then
  insert (program_id, delivery_type_id)
  values (src.program_id, src.delivery_type_id);


insert into program_languages (program_id, language_id)
select distinct p.program_id, l.language_id
from master_programs m
join programs p
  on p.program_name = trim(m.program_name)
 and p.university_id = (select u.university_id from universities u where u.university_name = trim(m.university_name))
cross join (select level as lvl from dual connect by level <= 10) t
join languages l
  on l.language_name = trim(regexp_substr(m.language_clean, '[^|]+', 1, t.lvl))
where m.language_clean is not null
  and regexp_substr(m.language_clean, '[^|]+', 1, t.lvl) is not null
  and not exists (
    select 1 from program_languages x
    where x.program_id = p.program_id and x.language_id = l.language_id
  );

insert into program_disciplines (program_id, discipline_id)
select distinct p.program_id, d.discipline_id
from master_programs m
join programs p
  on p.program_name = trim(m.program_name)
 and p.university_id = (select u.university_id from universities u where u.university_name = trim(m.university_name))
cross join (select level as lvl from dual connect by level <= 20) t
join disciplines d
  on d.discipline_name = trim(regexp_substr(m.disciplines_clean, '[^|]+', 1, t.lvl))
where m.disciplines_clean is not null
  and regexp_substr(m.disciplines_clean, '[^|]+', 1, t.lvl) is not null
  and not exists (
    select 1 from program_disciplines x
    where x.program_id = p.program_id and x.discipline_id = d.discipline_id
  );
  
insert into program_intakes (program_id, intake_month_date)
select distinct p.program_id,
       to_date('01.'||trim(regexp_substr(m.intake_month, '[^|]+', 1, t.lvl)), 'DD.MM.YYYY')
from master_programs m
join programs p
  on p.program_name = trim(m.program_name)
 and p.university_id = (select u.university_id from universities u where u.university_name = trim(m.university_name))
cross join (select level as lvl from dual connect by level <= 12) t
where m.intake_month is not null
  and regexp_substr(m.intake_month, '[^|]+', 1, t.lvl) is not null
  and not exists (
    select 1 from program_intakes x
    where x.program_id = p.program_id
      and x.intake_month_date = to_date('01.'||trim(regexp_substr(m.intake_month, '[^|]+', 1, t.lvl)), 'DD.MM.YYYY')
  );
  
insert into program_application_deadlines (program_id, deadline_month_date)
select distinct p.program_id,
       to_date('01.'||trim(regexp_substr(m.application_deadline_month, '[^|]+', 1, t.lvl)), 'DD.MM.YYYY')
from master_programs m
join programs p
  on p.program_name = trim(m.program_name)
 and p.university_id = (select u.university_id from universities u where u.university_name = trim(m.university_name))
cross join (select level as lvl from dual connect by level <= 12) t
where m.application_deadline_month is not null
  and regexp_substr(m.application_deadline_month, '[^|]+', 1, t.lvl) is not null
  and not exists (
    select 1 from program_application_deadlines x
    where x.program_id = p.program_id
      and x.deadline_month_date = to_date('01.'||trim(regexp_substr(m.application_deadline_month, '[^|]+', 1, t.lvl)), 'DD.MM.YYYY')
  );




merge into program_language_requirements d
using (
  with tokens as (
    select p.program_id,
           trim(regexp_substr(m.language_requirements_std, '[^|]+', 1, t.lvl)) as token
    from master_programs m
    join programs p
      on p.program_name = trim(m.program_name)
     and p.university_id = (select u.university_id
                            from universities u
                            where u.university_name = trim(m.university_name))
    cross join (select level as lvl from dual connect by level <= 10) t
    where m.language_requirements_std is not null
      and regexp_substr(m.language_requirements_std, '[^|]+', 1, t.lvl) is not null
  ),
  parsed as (
    select program_id,
           regexp_replace(trim(regexp_replace(token, '([0-9]+(\.[0-9]+)?)$', '')), '\s+', ' ') as test_name_norm,
           regexp_substr(token, '([0-9]+(\.[0-9]+)?)$') as score_str
    from tokens
  ),
  rolled as (
    select
      p.program_id,
      lt.language_test_id,
      max(case when score_str is not null then to_number(score_str) end) as required_score_number
    from parsed p
    join language_tests lt
      on lt.test_name = p.test_name_norm
    where p.test_name_norm is not null
    group by p.program_id, lt.language_test_id
  )
  select program_id, language_test_id, required_score_number
  from rolled
) s
on (d.program_id = s.program_id and d.language_test_id = s.language_test_id)
when not matched then insert (program_id, language_test_id, required_score_number, score_text)
values (s.program_id, s.language_test_id, s.required_score_number, null);

insert into program_study_options (program_id, study_mode_id, duration_months)
select
  t.program_id,
  sm.study_mode_id,
  max(t.duration_months) as duration_months
from (
  select
    p.program_id,
    trim(regexp_substr(m.study_mode, '[^|]+', 1, lvl)) as mode_token,
    case
      when m.study_mode_months is not null
           and regexp_like(trim(m.study_mode_months), '^[0-9]+(\.[0-9]+)?$')
      then to_number(trim(m.study_mode_months))
      else null
    end as duration_months
  from master_programs m
  join programs p
    on p.program_name = trim(m.program_name)
   and p.university_id = (
         select u.university_id
         from universities u
         where u.university_name = trim(m.university_name)
       )
  cross join (select level as lvl from dual connect by level <= 5)
  where m.study_mode is not null
    and regexp_substr(m.study_mode, '[^|]+', 1, lvl) is not null
) t
join study_modes sm
  on sm.study_mode_name = t.mode_token
where not exists (
  select 1
  from program_study_options x
  where x.program_id = t.program_id
    and x.study_mode_id = sm.study_mode_id
)
group by t.program_id, sm.study_mode_id;


